steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v1
    with:
      python-version: 3.7.4
  - uses: Gr1N/setup-poetry@v4
    with:
      poetry-version: 1.1.5
  - run: poetry --version
