---
name: Run unit tests
on: push

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7.11
      - uses: Gr1N/setup-poetry@v7
      - run: poetry install
      - run: poetry run pytest --verbose
